image: Visual Studio 2017

environment:
  CODECOV_TOKEN:
    secure: atEiGSGhgygzvo/dKLOwObQLMMFZyvsrW4rMT4VempTjJeLGw1SNHdlm1vxVwd0B

branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

build_script:
  - dotnet --info
  - dotnet tool install --global coverlet.console
  - ps: .\build.ps1 -LinkSources -Verbosity Verbose

test: off

artifacts:
- path: 'packaging\octokit*.nupkg'
  name: OctokitPackages